In [11]:
import pandas as pd
import numpy as np

In [12]:
incomes = [
    240000, 360000, 300000, 420000, 390000, 330000,
    310000, 370000, 315000, 345000, 280000, 410000,
    325000, 355000, 295000, 385000, 335000, 365000,
    320000, 350000, 8500000, 9200000, 400000, 305000,
    375000, 340000, 360000, 315000, 395000, 285000
]
df = pd.DataFrame({
    "income": incomes
})
df.head()

   income
0  240000
1  360000
2  300000
3  420000
4  390000

In [13]:
# IQR METHOD
q1 = df['income'].quantile(0.25)
q3 = df['income'].quantile(0.75)

IQR = q3 - q1

lower_bound = q1 - 1.5 * IQR
upper_bound = q3 + 1.5 * IQR

In [17]:
df['outlier'] = np.where((df['income'] > upper_bound) | (df['income'] < lower_bound), "Outlier", "Normal")
df.head()

   income outlier
0  240000  Normal
1  360000  Normal
2  300000  Normal
3  420000  Normal
4  390000  Normal

In [18]:
df['outlier'].value_counts()

outlier
Normal     28
Outlier     2
Name: count, dtype: int64

In [25]:
outlier_df = df[df['outlier'] == "Outlier"]
outlier_df['average'] = df['income'].mean().round(0)
outlier_df

     income  outlier   average
20  8500000  Outlier  909167.0
21  9200000  Outlier  909167.0

In [51]:
mean = df['income'].mean()
sd = df['income'].std()
cv = (sd/mean) * 100



print(f'Mean:', mean.round(2))
print(f'Standard Deviation:', sd.round(2))
print(f'CV:', cv.round(2),"%")

Mean: 909166.67
Standard Deviation: 2160917.78
CV: 237.68 %

In [46]:
cleaned_df = df.copy()
cleaned_df['income'] = cleaned_df['income'].clip(lower = lower_bound, upper= upper_bound)
cleaned_df['outlier'] = np.where((cleaned_df['income'] > upper_bound) | (cleaned_df['income'] < lower_bound), "Outlier", "Normal")
cleaned_df.head()

   income outlier
0  240000  Normal
1  360000  Normal
2  300000  Normal
3  420000  Normal
4  390000  Normal

In [47]:
cleaned_df['outlier'].value_counts()

outlier
Normal    30
Name: count, dtype: int64

In [50]:
clean_mean = cleaned_df['income'].mean()
clean_sd = cleaned_df['income'].std()
clean_cv = (clean_sd/clean_mean) * 100



print(f'Mean:', clean_mean.round(2))
print(f'Standard Deviation:', clean_sd.round(2))
print(f'CV:', clean_cv.round(2),"%")

Mean: 351416.67
Standard Deviation: 55130.85
CV: 15.69 %